apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-values-app
spec:
  source:
    repoURL: https://github.com/user/repo.git
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
