name: Pull Request Workflow
on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run tests
        run: |
          echo "Running tests for PR"
      - name: Code Linting
        run: |
          echo "Linting code..."
