---
- name: Deploy to Minikube
  hosts: minikube
  become: yes

  tasks:
    - name: Ensure kubectl is installed
      apt:
        name: kubectl
        state: present

    - name: Create Kubernetes namespace
      command: kubectl create namespace app
      ignore_errors: yes

    - name: Apply Kubernetes manifests
      command: kubectl apply -f jenkins/ci-cd/deployment.yaml -n my-namespace
