apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod
---
apiVersion: v1
kind: Pod
metadata:
  name: dev-pod
  namespace: dev
  labels:
    app: dev-app
spec:
  containers:
  - name: dev-container
    image: busybox
    command: ["sh", "-c", "sleep 3600"]
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: prod-pod
  namespace: prod
  labels:
    app: prod-app
spec:
  containers:
  - name: prod-container
    image: busybox
    command: ["sh", "-c", "sleep 3600"]
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: prod-service
  namespace: prod
spec:
  selector:
    app: prod-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007  # NodePort in the range 30000-32767
  type: NodePort
