apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: default
spec:
  provider:
    vault:
      server: "http://vault.default:8200"
      path: "kv"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "my-secret"
          key: "vault-token"
