apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  namespace: resource-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: app
        imagePullPolicy: Never

