repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
releases:
- name: "{{.Environment.Name}}-redis"
  namespace: default
  chart: bitnami/redis
  values:
    - password: "{{ .Values.password }}"
environments:
  default:
    values:
      - password: "easyPass"
  prod:
    values:
      - ./redis-values.yaml
      - myVar: Bla123
