version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data   # Map local 'data' directory to '/app/data' in container
    environment:
      FLASK_ENV: development
