apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ns-network-policy
  namespace: prod
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: dev
